import Head from "next/head";
import Header from "../components/Header";
import Feed from "../components/Feed";
import Modal from "../components/Modal";

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen">
      <Head>
        <title>Instagram Clone</title>
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="http://cdn.syncfusion.com/js/assets/external/jsrender.min.js"></script>
        <script src="http://cdn.syncfusion.com/15.1.0.33/js/web/ej.web.all.min.js">
          {" "}
        </script>
        <link
          rel="stylesheet"
          rel="nofollow"
          href="http://cdn.syncfusion.com/15.1.0.37/js/web/flat-azure/ej.web.all.min.css"
        />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/768px-Instagram_logo_2016.svg.png"
        />
      </Head>
      <Header />
      <Feed />
      <Modal />
    </div>
  );
}
